import Head from 'next/head'
import { Poppins } from 'next/font/google'
import Navigation from '@/components/navigation/Navigation'
import Header from '@/components/header/Header'
const poppins = Poppins({
  subsets: ['latin'],
  weight: '400'
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <main className={poppins.className}>
        <Header />
      </main>
    </>
  )
}
